spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # Put here your user name
    username: root
    # Put here your password
    password: root
    url: jdbc:mysql://localhost:3306/?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081